# Generated by Django 3.2.9 on 2022-12-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('vendor_code', models.CharField(max_length=150)),
                ('price', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('in_stock', 'В наличии'), ('by_order', 'Под заказ'), ('expected', 'Ожидается поступление'), ('not_available', 'Нет в наличии'), ('not_produced', 'Не производится')], max_length=50)),
                ('image', models.ImageField(upload_to='images/', verbose_name='Картинка')),
            ],
        ),
    ]
